version: "3.7"
# https://docs.docker.com/docker-for-mac/osxfs/
services:
  # screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
  # echo never > /sys/kernel/mm/transparent_hugepage/enabled
  # echo never > /sys/kernel/mm/transparent_hugepage/defrag
  redis:
    container_name: redis
    image: redis:5
    volumes:
    - redis:/data

  db:
    container_name: db
    image: postgres:11
    environment:
    - POSTGRES_USER=$PGUSER
    - POSTGRES_PASSWORD=$PGPASSWORD
    volumes:
    - postgres:/var/lib/postgresql/data

volumes:
  redis: {}
  postgres: {}
  node: {}
  bundle: {}
