version: "3.7"
# https://docs.docker.com/docker-for-mac/osxfs/
# `docker-compose up` automatically reads the override file and applies it.
services:
  db:
    env_file: .env # Be aware that this prevents any ARG or ENV settings from Dockerfile to be loaded
